### ISSUE TITLE
Remove included resources from `CDAArray.items()`

### ISSUE THREAD

**Issue by tomxor** [contentful/contentful.java#103]
Example code:

```java
CDAArray array = client.fetch(CDAEntry.class)
    .where("content_type", "foo")
    .all();
```

In case any entries in the response link to other published entries (possibly of different content types) - `array.entries()` will contain the linked resources as well, forcing the caller to filter the results.

```java
array.entries() // all entries
array.entriesNoIncludes() // top-level entries only (should be part of CDAArray)
```

names not finalized yet.

**Comment by grncdr** [comment]
I would expect the default behaviour to be what's being proposed as `array.entriesNoIncludes()`.

**Comment by tomxor** [comment]
@grncdr :+1:, though we'll have to bump the major version.

**Comment by grncdr** [comment]
> we'll have to bump the major version

:+1:
