### ISSUE TITLE
Very untestable

### ISSUE THREAD

**Issue by lsamayoa** [contentful/contentful.java#108]
I have been using this SDK alongside the CMA client.  Because of the abuse of protected fields and final classes has been making it imposible to test, or at least it is very hard to test against mocks of your clients.

**Comment by tomxor** [comment]
When designing this library the main reasons behind these choices were immutability and not polluting the public API with elements that are used internally/shouldn't be used publicly. That said, I can see how the current state of things would make it difficult to unit-test, specifically around creating mocks for the client itself and the various resource model classes.

**Comment by lsamayoa** [comment]
Most of the problems I am having are because there is no easy way to build instances of the objects generated by the api ex.`CDAEntry` and `CDAResource` subclases. Providing a way to generate stubs of those clases would make it far more testable. 

Mockito is not able to mock final classes so also getting rid of the `final` declaration would also be a great idea IMHO.

Solving this two problems would make it far less painful to mock and would not deviate to much from the original intent.

**Comment by mariobodemann** [comment]
As an early xmas present, we just release version 6.0.0, introducing non final modifiers on public classes ... :christmas_tree:

**Comment by lsamayoa** [comment]
![Me Gusta](http://www.cuantocabron.com/images/templates/me-gusta-template.jpg)
