### ISSUE TITLE
Update to Retrofit2 and OkHttp3

### ISSUE THREAD

**Issue by troyjperales** [contentful/contentful.java#114]
Is this on the roadmap or in progress?

**Comment by mariobodemann** [comment]
Hey,

I just put it on our roadmap, and we will tackle it soon. 

Thanks

**Comment by mariobodemann** [comment]
Update in progress. 

We'll also update managment api, so to release them both together. For now you can take a look at this `master` branch for upcoming version 7.0.0. 

Let me know what you think ...

**Comment by mariobodemann** [comment]
This one is addressed with https://github.com/contentful/contentful.java/releases/tag/java-sdk-7.0.0
