### ISSUE TITLE
ClassLoader.getResourceAsStream massively slowing down Contentful client init

### ISSUE THREAD

**Issue by mrsasha** [contentful/contentful.java#119]
Hi guys,

I don't know if you've noticed, but using `ClassLoader.getResourceAsStream` to read the `contentful_cda.properties` is massively slowing things down when initializing the client. I've noticed it takes more than 1s, so I forked it and replaced it with a java class, since it's being used for just one thing. It would be nice if you could do it in the original library though.

BTW, NimbleDroid also published an article on this: http://blog.nimbledroid.com/2016/04/06/slow-ClassLoader.getResourceAsStream.html.

**Comment by mariobodemann** [comment]
Hey, 

thank you for your input. It sounds like a good addition. We will take a look into it and put it on our roadmap accordingly ...

Thanks,
Mario
