### ISSUE TITLE
Querying Multiple Values FetchQuery

### ISSUE THREAD

**Issue by DonFuego** [contentful/contentful.java#123]
I'm noticing the FetchQuery has a protected method accepting .where(Map <String, String> params).  How do I utilize this within the SDK?  I'm trying to do something like this:

```
CDAArray entries = client.fetch(CDAEntry.class)
                .where("content_type", contentType)
                .where(**myKeyValueAttributeMap**)
                .where("order", ORDER_BY_CREATE_TIME)
                .where("include", "10")
                .all();
```

**Comment by mariobodemann** [comment]
Hey,

Right now I would see you can loop through your map and add the key/value pairs your self, as you probably just discovered your selve ... ;)

Greetings,
Mario
