### ISSUE TITLE
Is there a Contentful rest API for querying a list of entries

### ISSUE THREAD

**Issue by surju87** [contentful/contentful.java#129]
Is there a Contentful rest API for querying a list of entries? We do have an API for getting all entries of a content type or querying a single entry based on entryId but did not find any API for querying a list of entryIds.
@mariobodemann

**Comment by mariobodemann** [comment]
Hello @surju87,

I am not sure if I understood your question correctly, but afaik for getting all entries, you would use something like 

```
CDAArray entries = client.fetch(CDAEntry.class).all();
```

To get an array of entries, which are based on the base type of entries: `CDAEntry`.

I hope it helped,
Mario

**Comment by surju87** [comment]
Thanks @mariobodemann ,

currently i can fetch data for given entry or getting all entries data for given space_id but is there any rest api where i can provide you "list of entry_id's" and  can expect data for all given entries.

is it compulsory to use cda-sdk.jar or you have same in rest api's as well. ?

Thanks
Santosh Kumar

**Comment by mariobodemann** [comment]
Hey,

yes there is:

```
CDAArray entries = client.fetch(CDAEntry.class)
    .where("sys.id[in]", "id1,id2,id3,…")
    .all();
```

It uses the _inclusion_ feature mentioned in our[ api reference documentation](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/inclusion).
 
Please make sure to not make the request to big, the maximum length of the url this would request lays at 4096, aka if you need to request more then 64 entries, which can have up to 64 characters in id length each, you should try and split it up into several requests.

Greetings, 
Mario

**Comment by surju87** [comment]
Thanks @mariobodemann
