### ISSUE TITLE
How do I close response body for a request that returns CDAHttpException?

### ISSUE THREAD

**Issue by dchem** [contentful/contentful.java#141]
Hi, thanks for writing this SDK.

1. When an exception is thrown due to `BadRequest`, I get the following error:
```
WARN   [14:27:54.368] [OkHttp ConnectionPool] o.OkHttpClient -  A connection to https://cdn.contentful.com/ was leaked. Did you forget to close a response body?
```
Does the connection time out, and close automatically?

2. If not, what is the way to close the connection when this happens? Should `ErrorInterceptor` handle request failure by doing `response.close()` then and there? Or should `CDAHttpException` close it? Or is there a smart way of doing this by using `Call.Factory`?

Thank you.

**Comment by mariobodemann** [comment]
hello @dchem that is a great catch! I will close the body in an non successful return. Thanks for finding it, I'll update the sdk asap.
