### ISSUE TITLE
Ability to decorate default CallFactory

### ISSUE THREAD

**Issue by jsuresh** [contentful/contentful.java#142]
Currently, the builder method `CDAClient.builder()` setCallFactory makes it hard to augment the default Call.Factory

A valid use case for us is to decorate the current CallFactory, and add a caching layer, or, for a nice dev cycle, store the results of queries so we can develop in 'fake contentful' mode.

Currently, the only way to do this is to fork the following Call.Factory setup, that is, we have copied the following lines into our codebase

```
OkHttpClient.Builder okBuilder = new OkHttpClient.Builder()
          .addInterceptor(new AuthorizationHeaderInterceptor(clientBuilder.token))
          .addInterceptor(new UserAgentHeaderInterceptor(createUserAgent()))
          .addInterceptor(new ErrorInterceptor());
```

This isn't ideal, as we now have to make sure our fork is in-sync with upstream. Could we please expose the default Call.Factory in the library?

**Comment by mariobodemann** [comment]
Hello,

that sounds like a great idea. I will take a look into a solution there, and report back soon ... 

Thanks for the suggestion. 

Mario

**Comment by jsuresh** [comment]
Nice @mariobodemann thanks for this
