### ISSUE TITLE
RxJava 2 support

### ISSUE THREAD

**Issue by imperial-crystalline-recursion** [contentful/contentful.java#145]
Currently the library doesn't do RxJava 2. Are there any plans immediately in the works for adding support in for this? I'd be happy to fork and then open a PR if not.

**Comment by mariobodemann** [comment]
Hello @imperial-crystalline-recursion,

sadly we don't have the migration to RxJava 2 on our time line just now. Please feel free to fork and open a PR, I would be happy to take a look at it, thanks for the suggestion!

**Comment by mariobodemann** [comment]
@imperial-crystalline-recursion I am happy to inform you, that we have now a released version with RxJava 2. support: https://github.com/contentful/contentful.java/releases/tag/java-sdk-8.0.0 🎉

Please let us know what you think ....
