### ISSUE TITLE
validations field is null for single links

### ISSUE THREAD

**Issue by fmendezh** [contentful/contentful.java#146]
see his json schema: https://app.contentful.com/spaces/q553fnlofhvs/content_types/Event/preview --> {
      "name": "Primary Link",
      "id": "primaryLink",
      "type": "Link",
      "linkType": "Entry",
      "validations": [
        {
          "linkContentType": [
            "Link"
          ]
        }
      ],
      "localized": false,
      "required": false,
      "disabled": false,
      "omitted": false
    }…

but using the java api I get:
cdaField = {com.contentful.java.cda.CDAField@5550} 
 name = "Primary Link"
 id = "primaryLink"
 type = "Link"
 linkType = "Entry"
 disabled = false
 required = false
 localized = false
 items = null
 validations = null

please note that 'validations' is null in the java response

**Comment by mariobodemann** [comment]
Hello,

we had some internal discussions about this feature and agreed that the validations should _not_ be exposed on CDA, since we could imagine potential abuses/security scenarios (someone tries to figure out a flaw in out regexp validation? Or everyone would know the list of blocked words? Etc. etc.)

If you need the validations exposed, please consider using the management API. Additionally, please feel free to reach out to us, so we can take a look at your usecase. Maybe there is a different way to achieve your desired effects, without needing the CMA?

Anyway: Thank you for brining this to my attention, and sorry for the not positive news ... :(

**Comment by mariobodemann** [comment]
Sorry, I closed this issue a bit prematurely.

Looking at the [code you luckily linked](https://github.com/gbif/content-crawler/commit/dc64cbd3d3df2a209a3a5b3cf57f46cd78d51cc2#diff-fbb1eb495eb31dd6e8c585e26c8ae9f3R352), you are now using the CMA, to find out what type the arrays are linked to, right? 

For this specific instance of validation, we have the [linkType attribute in the SDK](https://github.com/contentful/contentful.java/blob/master/src/main/java/com/contentful/java/cda/CDAField.java#L15) and [documented here](https://www.contentful.com/developers/docs/concepts/links/#fetching-resources-linked-to-a-specific-entry). That would allow you to validate the type of an entry of an array without exposing and needing a CMA token.

Greetings, 
Mario

**Comment by fmendezh** [comment]
@mariobodemann thanks, for your response, I had switch to CMA API by the time I reported this issue and everything works fine there, initially, I found the API behavior a bit inconsistent because for Array fields I was able to get its 'validations', see this example:

8 = {com.contentful.java.cda.CDAField@5752} 
 name = "Funding Organisations"
 id = "fundingOrganisations"
 type = "Array"
 linkType = null
 disabled = false
 required = false
 localized = false
 items = {com.google.gson.internal.LinkedTreeMap@5762}  size = 3
  0 = {com.google.gson.internal.LinkedTreeMap$Node@5768} "type" -> "Link"
  1 = {com.google.gson.internal.LinkedTreeMap$Node@5769} "validations" -> " size = 1"
   key = "validations"
   value = {java.util.ArrayList@5781}  size = 1
    0 = {com.google.gson.internal.LinkedTreeMap@5796}  size = 1
     0 = {com.google.gson.internal.LinkedTreeMap$Node@5800} "linkContentType" -> " size = 1"
      key = "linkContentType"
      value = {java.util.ArrayList@5803}  size = 1
       0 = "Organisation"

Thanks, Fede.
