### ISSUE TITLE
Custom TLSSocketFactory failure on JBoss

### ISSUE THREAD

**Issue by mkxcode** [contentful/contentful.java#162]
When running the Contentful SDK on JBoss with the custom TLSSocketFactory enabled for TLS1.2 support, the operation keeps failing due to failure of the OkHttpClient finding the trust manager (probably fundamentally classloader related issues). This appears to be happening due to the call to okBuilder.sslSocketFactory() in CDAClient.java, which is a deprecated API. According to the recommendation from OkHttpClient, the trust manager should now be provided as parameter, probably precisely to prevent this kind of a problem from happening. Indeed, the following patch corrects the problem. Should you find this workable for you, it would be helpful if such a fix can be incorporated in future versions of the SDK.

(the patch is for v8.0.2 of the SDK, but the same call seems to still be present in 9.0.0)

```
diff --git a/src/main/java/com/contentful/java/cda/CDAClient.java b/src/main/java/com/contentful/java/cda/CDAClient.java
index 2581688..431997d 100644
--- a/src/main/java/com/contentful/java/cda/CDAClient.java
+++ b/src/main/java/com/contentful/java/cda/CDAClient.java
@@ -33,6 +33,11 @@ import static com.contentful.java.cda.build.GeneratedBuildParameters.PROJECT_VER
 import static com.contentful.java.cda.interceptor.ContentfulUserAgentHeaderInterceptor.Section.os;
 import static com.contentful.java.cda.interceptor.ContentfulUserAgentHeaderInterceptor.Section.platform;
 import static com.contentful.java.cda.interceptor.ContentfulUserAgentHeaderInterceptor.Section.sdk;
+import javax.net.ssl.TrustManagerFactory;
+import javax.net.ssl.X509TrustManager;
+import javax.net.ssl.TrustManager;
+import java.security.KeyStore;
+import java.util.Arrays;
 //END TO LONG CODE LINES

 /**
@@ -577,7 +582,16 @@ public class CDAClient {
     private OkHttpClient.Builder useTLS12IfWanted(OkHttpClient.Builder okBuilder) {
       if (useTLS12) {
         try {
-          okBuilder.sslSocketFactory(new TLSSocketFactory());
+          TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(
+            TrustManagerFactory.getDefaultAlgorithm());
+          trustManagerFactory.init((KeyStore) null);
+          TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();
+          if (trustManagers.length != 1 || !(trustManagers[0] instanceof X509TrustManager)) {
+            throw new IllegalStateException("Unexpected default trust managers:"
+              + Arrays.toString(trustManagers));
+          }
+          X509TrustManager trustManager = (X509TrustManager) trustManagers[0];
+          okBuilder.sslSocketFactory(new TLSSocketFactory(), trustManager);
         } catch (Exception e) {
           throw new IllegalArgumentException("Cannot create TLSSocketFactory for TLS 1.2", e);
         }
```

**Comment by mariobodemann** [comment]
Hey @mkxcode,

thanks for that recommendation. I'll add this to the next 9.0.1 release. There are some minor things I'm going to change though (!= 1 vs < 1, and adapting it to 9.x). 

But in general: Thank you for this recommendation, it makes the reflection and deprecation go away and seems more reasonable.

**Comment by mariobodemann** [comment]
A quick question: On which system are you using `useTls12`? Chances are that your system already provides a working and enabled tls12 installation. (JDK 1.7+ should already do it ...)

**Comment by mkxcode** [comment]
Thanks Mario. Glad you found it useful. This was found necessary on JDK 1.7 u70-80 and older. The need goes away on higher JDK7 versions (u161), but not all of the machines used are updated or easily updateable, so this support even on older versions is useful. Thank you very much.
