### ISSUE TITLE
Optional OkHttp dependency for Default Client

### ISSUE THREAD

**Issue by hoeggi** [contentful/contentful.java#165]
The readme states:
> The SDK uses Retrofit under the hood as a REST client, which detects OkHttp in your classpath and uses it if it's available, otherwise falls back to the default HttpURLConnection.
> The recommended approach would be to add okhttp-urlconnection as a dependency to your project (okhttp already included), but that is completely optional.

I think this is either wrong or poorly worded. OkHttp seems to be a hard dependency of the sdk and if you try to initialize a CDAClient without OkHttp on your classpath, it fails at runtime with a NoClassDefFoundError.

This can be reproduced with a simple project including the sdk this way:
```
    compile('com.contentful.java:java-sdk:9.0.1') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
```

**Comment by mariobodemann** [comment]
Hey,

that is a great find! I will update the README accordingly. (We do *not* support another http client then okhttp).

Thank you for finding it.

Greetings, 
Mario
