### ISSUE TITLE
Unit Testing - Mock Data

### ISSUE THREAD

**Issue by allanneves** [contentful/contentful.java#179]
Hi,
   I would like to know your recommendation for mocking contentful objects (especially CDAEntry) for unit testing purposes. Integration tests are easy as they fetch real-time information from your services but when it comes to unit testing methods that interact with a CDAEntry it is very painful. Even though an entry can be created and mocked, the data model I use in contentful is complex to be replicated due to nested content so this is definitely not a feasible option. I have checked your repo and noticed that you created your own annotations (Enqueue is an example of that) to consume a JSON file and parse that to the desired content in the Java language. I would like to do something similar: store a JSON file inside my application and mock the Contentful SDK structure based on that so I can test methods individually. How would you approach the problem and what is your recommendation for achieving that?

Thanks,
Allan

**Comment by narasimhulumgit** [comment]
I'm facing the same problem. Any solution?

**Comment by tlaredo** [comment]
Figured it out! In python, I just passed in a json representation of the raw response to the `Entry` constructor. E.g.

```
from contentful import Entry

def load_as_json(filename):
    with open(filename) as f:
        return json.load(f)

test_entry = Entry(load_as_json('path/to/response.json'))
```

**Comment by allanneves** [comment]
Hi @tlaredo, @narasimhulumgit.
    I ended up changing my own implementation to accommodate unit tests, I'm mocking a simple response using WireMock and working with that. Then I created a proxy object to have my own entries and am testing it this way, it is not ideal as it ties my model to any Contentful changes but it is what I could do at the time. I haven't been maintaining the application since 2019 so I'm not sure if Contentful has recently made testing easier in the Java API as it is in the Python Library.
