### ISSUE TITLE
Integrate with contentful with bff

### ISSUE THREAD

**Issue by ganesanarun** [contentful/contentful.java#185]
We have few backend services and everything is exposed through BFF, and content related to Mobile UI are going to be stored in contentful. When we return response to Mobile UI from BFF, we have to fetch the content which are related to domain object from contentful. We would like to abstract the contentful from Domain services, i.e., would not like to put the `EntryId` of a contentful into Domain service. 

For example, there are only questions with just `domain_question_identifier`, question_type (sex, smoker, etc) and `domain_choice_identifier` of choices and the respective question text and choices are stored in Contentful. How do we get question text and choice text from the domain identifiers, instead of putting the respective `EntryId`(ies) into domain data store?

Could any of you help us on that?

**Comment by mariobodemann** [comment]
Hey,

that sounds like a usecase for https://github.com/contentful/vault. With vault you will fetch the complete dataset only once and will be creating your own models. References are resolved on the fly.

Happy checking out.

Mario

**Comment by mariobodemann** [comment]
> I am closing this ticket due to inactivity. Please feel free to open up a new one if needed.
