### ISSUE TITLE
Rich Text Parser

### ISSUE THREAD

**Issue by dmnt3rr0r** [contentful/contentful.java#187]
Hello, I am using scala to build our contentful integration which has meant that I am using the rest api to access the content. Everything has worked nicely up-until I have run across a rich text field. I see you have support for rich text in the library to some degree... is there a way to use the parser outside the context of CDAEntry to convert the rich text to markdown for example? If so, can you provide a little snippet of java code that does this? Thank you.

**Comment by mariobodemann** [comment]
Hello,

thank you for using our REST API.

Sadly, you cannot extract the RichText parsing easily. You could try and get 'inspired' by the [RichTextFactory](https://github.com/contentful/contentful.java/blob/master/src/main/java/com/contentful/java/cda/rich/RichTextFactory.java), and use it's `resolve` method but we have no experience doing so and I'd expect that there would be quite some changes from the CDA* types to your own ones.

If I may ask bluntly: Would you mind sharing why you did not use the Java SDK? I was under the impression that a) we have other clients using scala and this sdk and b) scala and java are interoperable.

Greetings,
Mario

**Comment by matteo5883** [comment]
Hi, I'm using SDK to retrieve templates from contentful and I'm having problem parsing CDARichDocument element. Is there a way to retrieve a CDARichDocument field as a String?  I would like to generate a JSON document starting from the CDAArray retrieved from contentful via CDAClient.fetch method.
Thanks

**Comment by mariobodemann** [comment]
> Hi, I'm using SDK to retrieve templates from contentful and I'm having problem parsing CDARichDocument element. Is there a way to retrieve a CDARichDocument field as a String? I would like to generate a JSON document starting from the CDAArray retrieved from contentful via CDAClient.fetch method.
> Thanks

Hey @matteo5883 I created a new issue for the new issue. I'll answer it there.

**Comment by mariobodemann** [comment]
@dmnt3rr0r Hey, I will close this issue due to inactivity.
