### ISSUE TITLE
CDARichDocument as a String?

### ISSUE THREAD

**Issue by mariobodemann** [contentful/contentful.java#189]
Hi, I'm using SDK to retrieve templates from contentful and I'm having problem parsing CDARichDocument element. Is there a way to retrieve a CDARichDocument field as a String?  I would like to generate a JSON document starting from the CDAArray retrieved from contentful via CDAClient.fetch method.
Thanks

_Originally posted by @matteo5883 in https://github.com/contentful/contentful.java/issues/187#issuecomment-482492062_

**Comment by mariobodemann** [comment]
Hey @matteo5883,

sadly it is not possible to create a string representation.

Would you mind sharing on your issues parsing the generated nodes?

Greetings,
Mario

**Comment by matteo5883** [comment]
And some sort of template?
If I have to retrieve content from contenful, if someone creates a RichText then I receive a json unreadable. 
For an ordered list I receive a series of nested list and in the leafs there are the CharSequence elements. For example if the RichText is something similar to the text below:

"1.hello;
2.world;
3. My name is matteo
This is a simple example
"
to parse this simple paragraph I have to inspect a series of nested lists and of different types (one should be CDARichOrderedList and one CDARichParagraph if I'm not wrong). 
Instead I would like to receive a template with HTML code or something like "1.hello;\n2.world;\n3. My name is matteo\nThis is a simple example"

**Comment by mariobodemann** [comment]
Hey,

I can see your troubles. Therefore we created the [RichtTextRenderer.java](https://github.com/contentful/rich-text-renderer.java). This project can work as an inspiration on rendering rich text into HTML.

**Comment by mariobodemann** [comment]
> Closing this issue and redirecting to RichTextRenderer.java.
