### ISSUE TITLE
client.sync(space).fetch() returns everything, expect only updates

### ISSUE THREAD

**Issue by PeterNilssonDev** [contentful/contentful.java#193]
When calling sync a second time (using before returned space variable) we expect only updated items/entries/assets etc to be returned. Current behavior is like doing an initial sync call every time

Using
```
        <dependency>
            <groupId>com.contentful.java</groupId>
            <artifactId>java-sdk</artifactId>
            <version>10.4.0</version>
        </dependency>
```

Using the following code:
```
        CDAClient client = CDAClient.builder()
                .setSpace("foo")
                .setToken("bar")
                .build();
        SynchronizedSpace space = client.sync().fetch();
        System.out.println(space.entries().size());
        SynchronizedSpace later = client.sync(space).fetch();
        System.out.println(later.entries().size());
```

Output (in our example):
1405
1405

Expected outout:
1405
0

If we use the "hack" `SynchronizedSpace later = client.sync(space.nextSyncUrl().split("=")[1]).fetch();` then 0 is returned.

**Comment by mariobodemann** [comment]
Hey,

you found a nice side condition: The intention of using a syncSpace for a sync is to fill it up with the actual changed resources. So it is expected to get the exact same number, since the second time no new resources got added.

If you are keen on seeing the second time only the updated resources, you could sync by a sync id:

```
SynchronizedSpace reallast = client.sync(space.nextSyncUrl().split("=")[1]).fetch();
System.out.println(reallast.entries().size());
```
This will give you only the updated resources.

I hope that helps, 
Mario

**Comment by PeterNilssonBonnier** [comment]
Ok, I see. So how do we detect changes when calling sync using ```client.sync(space).fetch();```? As you describe it, it seems like ```client.sync(space).fetch();``` and ```client.sync().fetch();``` both returns the same data.

**Comment by mariobodemann** [comment]
Hey, 

just as you described: If your last space contains the same amount of entries then the current space, there was no change, unless an element got added and another one got deleted, or there are some field changes in between. 

If you are interested then just the complete set of resources, but actually want to find out what changed, please feel free to use the `sync_token` as described by you and me above.
