### ISSUE TITLE
cdaClient.observeAndTransform(ArticleResponse.class).include(1) doesn't resolve link 

### ISSUE THREAD

**Issue by vittalbh** [contentful/contentful.java#199]
I am trying to fetch all the articles from Contentful and transform them to ArticleResponse (Java Model) each article inturn have CDAAsset(which is an image link) . To resolve link and get the image contents i am caling _include(1)_ 
 
Using below dependenices
` compile 'com.contentful.java:java-sdk:10.4.0'`

Below is the source code

```
final Flowable<Collection<ArticleResponse>> currentPagedItems = cdaClient
                .observeAndTransform(ArticleResponse.class)
                .include(1)
                .limit(PAGE_SIZE)
                .orderBy("sys.createdAt")
                .all();
```

I am getting below reponse output for image field, which is absolutely empty
"bannerImage": {},

Expected output:
it should be image content as byte[]

what is issue here??

**Comment by PankajS24** [comment]
Try to use .include(10) 10 is MAX

**Comment by rafalniski** [comment]
@PankajS24 Suggested possible solution.
