### ISSUE TITLE
Asset data is populated only under the raw data of the entry content, while structured fields miss that data under the CDARichEmbeddedBlock

### ISSUE THREAD

**Issue by drezzzik** [contentful/contentful.java#201]
Version of the library: 10.4.1
Screenshot attached:
![Screen Shot 2019-09-18 at 11 18 22](https://user-images.githubusercontent.com/54620131/65136202-768ba400-da07-11e9-99e8-764dea4fe7e7.png)
As you can see, the data object is empty for CDARichEmbeddedBlock whilst it could be found under rawFields.

Nice to have: CDARichEmbeddedBlock::data is Object. Would be convenient to have all that sys structure with id, linkType and type in there.

Any field which is Media type behaves the same, data is missing in entry.fields while present in entry.rawFields.

**Comment by denrase** [comment]
+1

**Comment by drezzzik** [comment]
Seems that source of the problem is next:
1st case: client.sync(SyncType.onlyEntriesOfType("someContentType")).observe().blockingFirst()​.entries()
2nd case: client.sync().observe().blockingFirst().entries.filter { it.value.contentType().id() == "someContentType" }

Result is not the same. If the filtering is done by SyncType, problem described above is reproducible. For the 2nd case, issue is not repro, and both rawFields and fields contain same data.
