### ISSUE TITLE
ClassCastException when used with spring-dev-tools

### ISSUE THREAD

**Issue by kishore-pothireddy** [contentful/contentful.java#207]
Hi,

We are using the contenful SDK along with spring-dev-tools. When tried to deserialize the contentful response into custom types using observeAndTransform() method its throwing ClassCastException.
Its working fine when commented out the spring-dev-tools dependency.

Below doc says it is a known limitation.
https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html#using-boot-devtools-known-restart-limitations 

Any thoughts on this? How can we fix it?

**Comment by rafalniski** [comment]
Hey @kishore-pothireddy,

as I correctly understand the reason for this `ClassCastException` is using GSON library as our serializer/deserializer. It uses `ObjectInputStream` when serializing/deserializing. Unfortunately, we don't have plans for changing the library or supporting `ConfigurableObjectInputStream` in the near future.

**Comment by calaily** [comment]
@kishore-pothireddy I ran into a similar issue. What worked for me was creating a `src/main/resources/META-INF/spring-devtools.properties` file and adding `restart.include.contentful=java-sdk-10.4.0.jar` to it.
