### ISSUE TITLE
Retrieve specific locale using observeAndTransform

### ISSUE THREAD

**Issue by kelmer44** [contentful/contentful.java#208]
Documentation indicates this is done through annotation, but I only figure out what my locale is on runtime, so I would need to be able to request a specific locale on my rxjava2 request Builder.

I saw `withLocale()` was added on some commit but I cant find it anywhere on the SDK?

**Comment by ktiniatros** [comment]
You can pass the locale in their query like this:
```
client
            .observeAndTransform(FAQEntryData::class.java)
            .where("locale", "nl-BE")
            .all()
            .map {
                it.toList()
            }
```
