### ISSUE TITLE
Usage of java.util.Optional crashes in API-21 for Android

### ISSUE THREAD

**Issue by VenomVendor** [contentful/contentful.java#213]
As per docs, SDK must support API-21 in Android. With the usage of [`java.util.Optional`](https://github.com/contentful/contentful.java/blob/db016cb75b5792db6612e2faae4960ee4990a72d/src/main/java/com/contentful/java/cda/AbsQuery.java#L5), SDK crashes. Optional was added in [API-24](https://developer.android.com/reference/java/util/Optional).

**Comment by bizon91** [comment]
Hi, got same issue. Seems as they use java.util.Optional only in `withLocale` function. I replaced `withLocale(locale)` with `where("locale", locale)` in query and it's working on devices below API 24.

**Comment by rafalniski** [comment]
@bizon91 @VenomVendor This should be fixed by PR #214 Will let you know once it's released.

**Comment by VenomVendor** [comment]
With latest release of Android Studio 4.0+, this is not an issue any more.
Ref : https://developer.android.com/studio/releases#4-0-0-desugar
