### ISSUE TITLE
Linked entries - Response size too big. Maximum allowed response size: 7340032b.

### ISSUE THREAD

**Issue by swapnil1689** [contentful/contentful.java#218]
Hello,

Getting following error when fetching linked entries using CdaClient (preview) with include=10,

{
  "sys": {
    "type": "Error",
    "id": "BadRequest"
  },
  "message": "Response size too big. Maximum allowed response size: 7340032b.",
  "requestId": "8190b9178297e1b076c3553f5b0d252f"
}

If I change the include to 9, I get the response.

In many articles I see suggestions to use limit and skip. But how can one resolve the issue in case of linked entries?

**Comment by rafalniski** [comment]
This is a limitation on the backend side. Closing for now, please reopen it if the issue still persists on your side.
