### ISSUE TITLE
JSON fields with integers are returned as doubles

### ISSUE THREAD

**Issue by PatrickBuTaxdoo** [contentful/contentful.java#219]
I save JSON data in Contentful. Some fields are saved as integers, i.e. as numbers without decimal part.

When I retrieve the JSON using the Contentful Java SDK, the JSON is already parsed with Gson, and the response contains the numbers as doubles, not as integers. Gson unfortunately always parses numbers to doubles.

Is there any way to get the raw JSON string, or to get the numbers as Integers?

**Comment by brian-1d3** [comment]
This is still an issue

**Comment by amondnet** [comment]
#235

**Comment by adrian-skybaker** [comment]
Unsure why this was closed, this is still an issue.
