### ISSUE TITLE
CDAHttpException fails to call super

### ISSUE THREAD

**Issue by AndyGee** [contentful/contentful.java#221]
https://github.com/contentful/contentful.java/blob/573158ee6ba6c9268ce09587bba9ce08c758f4ea/src/main/java/com/contentful/java/cda/CDAHttpException.java#L36

This Exception should call super to seed the underlying message.

Currently #getMessage returns null

**Comment by rafalniski** [comment]
@AndyGee Should be fixed by https://github.com/contentful/contentful.java/pull/234
