### ISSUE TITLE
This SDK requires Android 7 (not Android 5 as described)

### ISSUE THREAD

**Issue by kaidotarma** [contentful/contentful.java#223]
com.contentful.java.cda.AbsQuery uses Optional.ofNullable, which is not supported by Android 5 nor 6.
So only Android 7 (API 24) + is supported right now.

**Comment by kaidotarma** [comment]
https://github.com/contentful/contentful.java/pull/224

**Comment by rafalniski** [comment]
Hey, thanks, that will be release soon with 10.4.5 version

**Comment by rafalniski** [comment]
It's shipped.
