### ISSUE TITLE
Can CDAClient fetch raw representation of RichText fields, instead of CDARichDocument?

### ISSUE THREAD

**Issue by gediminasmorkys** [contentful/contentful.java#230]
We fetch data trough the Java SDK and serve dtos to frontend, where the data gets rendered. Everything works great with @ContentfulField annotations, so thank you for all the work on this library.

We run into issues when we want render RichText fields. In frontend we use @contentful/rich-text-html-renderer.

When fetching entries with RichText fields from Contentful over e.g. curl, we get something that can be rendered with @contentful/rich-text-html-renderer, e.g.:

```
{
  "data": {},
  "content": [
      {
          "data": {},
          "content": [
              {
                  "data": {},
                  "marks": [],
                  "value": "Some text",
                  "nodeType": "text"
              }
          ],
          "nodeType": "paragraph"
      }
  ],
  "nodeType": "document"
}
```

However, CDAClient.fetch retrieves RichText fields as CDARichDocument instances, and those look like this:

```
{
  "content": [
    {
      "content": [
        {
          "marks": [],
          "text": "Some text"
        }
      ]
    }
  ]
}
```

CDARichDocument does not keep the same structure as the raw data in the RichText field (for starters, a “value“ becomes “text”, and there is no more nodeType field).

So RichText field becomes unusable to frontend clients that want to put RichText straight to html.

I really like the @ContentfulField helper, but also want to get usable RichText.

Is there a way to use the Contentful java-sdk to get raw RichText fields information at all?

**Comment by rafalniski** [comment]
Unfortunately, we don't have plans currently to add this to Java library.

**Comment by MarcBeaujean** [comment]
Why not? Surely this is the most common use of the rich text field....

**Comment by benmarch** [comment]
We're now running into this issue as well. We have a BE service that authorizes and makes requests to Contentful, then essentially just forwards the results to the FE. But because of this, the FE is not able to use the JS SDK with `documentToReactComponents`. Can you please reconsider adding this feature or suggest an alternative approach?

**Comment by rafalniski** [comment]
Hey @benmarch, @gediminasmorkys,

we provide a separate library for rendering the RichText to HTML - [https://github.com/contentful/rich-text-renderer-java/tree/master/html](https://github.com/contentful/rich-text-renderer-java/tree/master/html) - you are also able to implement a custom renderer. Let me know if it fits your needs.

**Comment by benmarch** [comment]
Hey @rafalniski, thank you for the quick reply. Unfortunately, that will not work for our needs. We need the FE to be able to use the Contentful JS SDK for rendering the Rich Text to React components, which would require the Rich Text JSON to pass through unchanged from the Java side. 

It would be great if we could set the field type in the POJO to `String` or `Map<String, Object>` or `JSONElement` to get the raw structure from the Contentful API instead of parsing it. 

Alternatively, if this library parsed the Rich Text in a way where it keeps the same structure when it re-serializes then that would also fit our needs. Thanks!

**Comment by junhuhdev** [comment]
This is how I solved it currently, as a workaround

```java

public Object parseRichDocument(CDAResource item, String fieldName) {
		try {

			String entryId = item.getAttribute("id");

			final CDAEntry entry = client.fetch(CDAEntry.class)
					.include(10)
					.withLocale(DEFAULT_LOCALE)
					.one(entryId);

			Map<String, Object> richDocuments = (Map<String, Object>) entry.rawFields().get(fieldName);
			return richDocuments.get(DEFAULT_LOCALE);
		} catch (Exception e) {
			log.error("Error parsing rich document: " + e.getMessage() + " for field: " + fieldName);
			return null;
		}
	}
```

Which will give me the following json response 

```json
{
  "nodeType": "document",
  "data": {},
  "content": [
    {
      "nodeType": "paragraph",
      "data": {},
      "content": [
        {
          "nodeType": "text",
          "value": "Apple ",
          "marks": [],
          "data": {}
        },
        {
          "nodeType": "text",
          "value": "test phone",
          "marks": [
            {
              "type": "bold"
            }
          ],
          "data": {}
        },
        {
          "nodeType": "text",
          "value": " more text. ",
          "marks": [],
          "data": {}
        },
        {
          "nodeType": "hyperlink",
          "data": {
            "uri": "/link"
          },
          "content": [
            {
              "nodeType": "text",
              "value": "Link In the middle",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "text",
          "value": " example text",
          "marks": [],
          "data": {}
        }
      ]
    },
    {
      "nodeType": "heading-2",
      "data": {},
      "content": [
        {
          "nodeType": "text",
          "value": "This should be header#2",
          "marks": [],
          "data": {}
        }
      ]
    },
    {
      "nodeType": "paragraph",
      "data": {},
      "content": [
        {
          "nodeType": "text",
          "value": "",
          "marks": [],
          "data": {}
        },
        {
          "nodeType": "hyperlink",
          "data": {
            "uri": "http://example.com"
          },
          "content": [
            {
              "nodeType": "text",
              "value": "Example Link",
              "marks": [],
              "data": {}
            }
          ]
        },
        {
          "nodeType": "text",
          "value": "",
          "marks": [],
          "data": {}
        }
      ]
    }
  ]
}
```

**Comment by benmarch** [comment]
Thanks @junhuhdev! Does that require you to make 2 requests if you want to use the raw Rich Text but still transform the rest of the entry?

**Comment by junhuhdev** [comment]
Np @benmarch 

Yeah i think so. But I think u can do with one request depending on how nested ur content is.  By defining the include tag, max is 10.

```java
			var hardwareEntries = client.fetch(CDAEntry.class)
					.withContentType("mobiles")
					// Retrieval of linked items
					// default is 1
					.include(10)
					.all();

```



A complete different approach would be to do a normal HTTP request 

GET https://api.contentful.com/spaces/iidtcybzv1rq/environments/target/entries/{entryId}/references?include=10

if you want to work with raw json data as close as possible. You need setup an access token if u go this route. It's not same token u use in the java api client.

**Comment by benmarch** [comment]
Gotcha, thanks! I think this will work as a stop-gap, but ideally this library would implement either:

1. A way to pass the Rich Text JSON unchanged when using the TransformQuery client, or
2. A way to use the regular FetchQuery client, but then transform the `CDAEntry` after (so that the raw Rich Text can be extracted, but the rest of the entry can be transformed)

These will prevent the need for making two requests: one for the raw content, and one for the transformed content.

**Comment by gediminasmorkys** [comment]
> Hey @rafalniski, thank you for the quick reply. Unfortunately, that will not work for our needs. We need the FE to be able to use the Contentful JS SDK for rendering the Rich Text to React components, which would require the Rich Text JSON to pass through unchanged from the Java side.
> 
> It would be great if we could set the field type in the POJO to `String` or `Map<String, Object>` or `JSONElement` to get the raw structure from the Contentful API instead of parsing it.
> 
> Alternatively, if this library parsed the Rich Text in a way where it keeps the same structure when it re-serializes then that would also fit our needs. Thanks!

We also have the setup where frontend uses the https://github.com/contentful/rich-text for rendering html. Being able to provide them with the right input (raw Contentful rich text json structures) is the reason I am interested in this.

We have worked around this by implementing our own classes for RichTextDocument (containing a custom RichTextMark), to which we map to from a @ContentfulField CDARichDocument that we get after fetching with the TransformQuery client. This works well for the time being: there is just one fetch, but we need to do extra mapping. 

It would be nice to have this feature out of the box though :)
