### ISSUE TITLE
Embedded Entries within lists and blockquotes are not resolved

### ISSUE THREAD

**Issue by q-maro** [contentful/contentful.java#247]
Hi, 
similar to the issue here: https://github.com/contentful/rich-text-renderer-java/issues/16  we do not get resolved Entries in lists(ordered and unordered) and in blockquotes.
The problem is not in the rich-text-renderer-java, but in the contentful client contentful.java.

Here is an image, where the Embedded Inline Entry is not resolved (because it is inside a list). It shows the tree of a CDARichDocument.
![image](https://user-images.githubusercontent.com/4234918/162452962-2731223d-b0d5-4b60-a715-b1ba321c52c7.png)

Here is an image, where the Embedded Inline Entry is resolved (because it isn't inside a list, just plain in a paragraph). It shows the tree of a CDARichDocument.
![image](https://user-images.githubusercontent.com/4234918/162453329-03a18fde-89ff-4458-a497-d7a4ef43a643.png)

Here is an image of the content:
![image](https://user-images.githubusercontent.com/4234918/162454349-aa1aaea5-7981-4ce3-8c45-6a639331d973.png)

Would it be possible to add entry resolution inside unordered&ordered lists and blockquotes?
The problem is the same for block entries as for inline entries.

Best regards,
maro

**Comment by rafalniski** [comment]
Hey @q-maro 
thanks for the explanation, I started looking into that. Would you please paste here the code that triggers this?

**Comment by q-maro** [comment]
Hi @rafalniski , great to here!

Here is the Code:
```
contentfulClient.getClient()
                    .observeAndTransform(CfArticlePage.class)
                    .include(10)
                    .one(articlePageId)
                    .blockingFirst();
```
                    
Where articlePageId is an ID of an entry of type articlePage.
And CfArticlePage.class is a simple DTO inside our application:
`
@ContentfulEntryModel("articlePage")
public class CfArticlePage {
    @ContentfulSystemField
    private String id;

    @ContentfulField
    private String title;

    ... ... ...

    @JsonSerialize(converter = CDARichDocumentToStringConverter.class)
    @ContentfulField
    private CDARichDocument content;
}`

Do you need more information?

Best regards,
maro

**Comment by rafalniski** [comment]
Hey @q-maro,

Fix for that should be on the `fix/ISSUE-247-embedded-entries_within_list_error` branch if you want to check it and build locally. I plan to create a new release that will include it by the end of this week.

**Comment by rafalniski** [comment]
Should be fixed in v.10.5.3.

**Comment by q-maro** [comment]
Hi @rafalniski ,

this works exactly how i would expect it. Thank you very much!

Best regards,
maro
