### ISSUE TITLE
Stable release rxjava3

### ISSUE THREAD

**Issue by jmzg93** [contentful/contentful.java#250]
Hello,
When is it planned to release the stable version with rxjava3?

Old version of Flowable, Maybe, Single, etc
<img width="850" alt="image" src="https://user-images.githubusercontent.com/11294448/168833438-5c77eaaf-d51f-44be-b6fc-6f526651ff66.png">
New version: 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/11294448/168833652-24e0e0c4-7f5e-4d7c-a564-ffb8bcc90c4f.png">

The 2.x version is end-of-life as of February 28, 2021. No further development, support, maintenance, PRs and updates will happen. The Javadoc of the very last version, 2.2.21, will remain accessible.
Thanks in advance and greetings.

**Comment by petrosdeb** [comment]
Hi Jose,

I created [this issue](https://github.com/contentful/contentful.java/issues/249) requesting the same.

**Comment by rafalniski** [comment]
v.10.5.3 is released.
