### ISSUE TITLE
"select" method not working when using TransformQuery

### ISSUE THREAD

**Issue by guldner** [contentful/contentful.java#253]
Using 10.5.3-SNAPSHOT.

This "select" works:
```
client
    .observeAndTransform(MyClass.class)
    .where("select", "sys,fields.foo,fields.bar")
    .all().blockingFirst();
```
but this doesn't:
```
client
    .observeAndTransform(MyClass.class)
    .select("fields.foo", "fields.bar")
    .all().blockingFirst();
```
It returns all fields.
Something I'm doing wrong?

I haven't checked if `.select()` works with `fetch()` since I want to use unwrapping.

Btw, when using `where()` I still have to add "sys" to the list of fields or I'll get a NPE ([issues/134](https://github.com/contentful/contentful.java/issues/134))

**Comment by q-maro** [comment]
Did you try it without the select? The unwrapping happens magically by passing your Data-transfer-Object inside .observeAndTransform().

MyClass.class should have attributes, that are annotated with 
@ContentfulSystemField
or
@ContentfulField

The class itself is annotated with 
@ContentfulEntryModel("YOURCONTENTTYPE")

The .where() is typically used for filtering fields, not for selectiing the output.

**Comment by guldner** [comment]
@q-maro Thanks. Yes, everything works fine without the select. (or with  where("select", ...))

On the README page it says: "The amount of data returned by the API can be reduced by using the .select() method on a query." 
So I wanted to use it to reduce payload when I'm only interested in a slimmed down version of the entity.

I'm just going to use where(). But I believe the select method should work also, and it seems to me it doesn't when using unwrapping.
