### ISSUE TITLE
nodeType "table" not included in CDAEntry

### ISSUE THREAD

**Issue by michelklein** [contentful/contentful.java#257]
Hello everybody,

i am using version 10.5.4 and i am trying to render CDARichDocument as HTML in my Java backend code. My rich text field in Contentful contains several different elements including tables. In my java backend code I realized that the CDAEntry doesn't include the table inside the CDARichDocument. I also noticed that there is no corresponding Java class that could represent a table. Other html elements like hyperlinks, paragraphs have their own java representation (CDARichHyperLink, CDARichParagraph, ...) 

Is there a way to retrieve tables through the CDAClient in Java? Is this feature planned for the future?

**Comment by rafalniski** [comment]
Hey @michelklein,

rich-text tables are not yet supported in the library. The feature is planned for the next release.

**Comment by samcuth** [comment]
Hey @rafalniski,

I'm also interested in this. Do you have an ETA for the next release yet? And are you able to confirm whether rich-text tables are still planned for it?

Cheers

**Comment by rafalniski** [comment]
hey @samcuth ETA is middle of the next week.

**Comment by samcuth** [comment]
Excellent news! Thanks @rafalniski

**Comment by rafalniski** [comment]
@samcuth Hey, it's now available in `v.10.5.6`
