### ISSUE TITLE
Embedded inline entry within table in RTE not being resolved in returned fields 

### ISSUE THREAD

**Issue by haydnsimons** [contentful/contentful.java#265]
When calling CDAClient.fetch method to retrieve a piece of content from Contentful which includes an RTE with a table which includes embedded inline entries in it, these entries aren't resolved to CDAEntry objects as they are elsewhere. I've written a demo application below to show exactly what methods i'm using.

```
import com.contentful.java.cda.CDAClient;
import com.contentful.java.cda.CDAEntry;

public class Application {

private final static String TOKEN = "PERSONAL_ACCESS_TOKEN";
private final static String SPACE = "SPACE_ID";
private final static String ENVIRONMENT = "ENVIRONMENT";

    public static void main(String[] args) {

        CDAClient client = CDAClient.builder()
                    .setSpace(SPACE)
                    .setToken(LIVE_TOKEN)
                    .setEndpoint("https://cdn.contentful.com/")
                    .setEnvironment(ENVIRONMENT)
                    .build();
                    
        cdaEntry = client
        .fetch(CDAEntry.class)
        .include(10)
        .one(entryId);
    }
}
```
### Example

**In the example below I have a RTE which contains a list with an embedded inline entry and also a table which contains two embedded inline entries, one in the header cell and one in the cell below:**

![a1](https://user-images.githubusercontent.com/108814133/186666791-6d612941-da70-430b-8b17-bc190bca44d9.png)

**This returns:** 

![a2](https://user-images.githubusercontent.com/108814133/186667297-0caf6016-478a-42ce-a5a6-f00e48137fab.png)

Which looks correct so far (CDARichParagraph, CDARichUnorderedList, CDARichTable, CDARichParagraph & CDARichParagraph)

**When you dig further in to see the embedded inline entries, you can see that the one within the CDARichUnorderedList shows as  a CDAEntry object as expected but the one within the CDARichTable still shows as raw data (LinkedTreeMap which contains a target)**

![a3](https://user-images.githubusercontent.com/108814133/186667973-cfbf737e-6264-4855-b616-692472ea8e10.png)

**This is currently preventing us using embedded inline entries within tables within an RTE.**

**Could you confirm this is an issue and keep me updated on when it may be resolved?**

Thanks!

**Comment by rafalniski** [comment]
Hey @haydnsimons this was indeed an issue, thanks for catching that.
I created a fix here: https://github.com/contentful/contentful.java/pull/266
Will make a new release early next week.

**Comment by rafalniski** [comment]
@haydnsimons This should be fixed in latest release.
