### ISSUE TITLE
How to unwrap images using transform query in JAVA SDK as CDAAsset is not serializable ?

### ISSUE THREAD

**Issue by ritz0106** [contentful/contentful.java#270]
How to handle unwrapping using transformquery in java sdk for image attribute as CDAAsset cannot be unwrapped? for example

@TransformQuery.ContentfulEntryModel("article")
public class Article implements Serializable {
@TransformQuery.ContentfulField("image")
private CDAAsset image;

@TransformQuery.ContentfulField("title")
private String title;

@TransformQuery.ContentfulField("description")
private String description;

@TransformQuery.ContentfulField("link")
private String link;
}
it fails with content type CDAAsset not able to serailize

**Comment by rafalniski** [comment]
Hey @ritz0106 

if you take a look at sample test here: https://github.com/contentful/contentful.java/blob/master/src/test/java/com/contentful/java/cda/integration/Integration.java#L708 unwrapping is possible for `CDAAsset` fields. `CDAAsset` is also serializable, so maybe removing implementing `Serializable` interface for `Article` will help.

**Comment by rafalniski** [comment]
Please reopen if the issue still happens
