### ISSUE TITLE
Unwrapping not working with link resolution

### ISSUE THREAD

**Issue by shikhar-truminds** [contentful/contentful.java#276]
Hi,

I am using the Contentful Java SDK version 10.5.9. I have a content model with many levels of nested entries. While fetching the data using CDAClient, the data for one particular model is not getting populated/unwrapped even though data exists in contentful.

Attaching the relevant code snippets:
Base Level Entry

```
import com.contentful.java.cda.TransformQuery.ContentfulEntryModel
import com.contentful.java.cda.TransformQuery.ContentfulField
import com.contentful.java.cda.TransformQuery.ContentfulSystemField


@ContentfulEntryModel("libraryMeetingPlace")
class CMSMeetingPlaceContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("tenantListPage")
    val tenantListPage: CMSTenantListContentfulDTO? = null
}
```

First Nested Entry
```
import com.contentful.java.cda.TransformQuery.ContentfulField
import com.contentful.java.cda.TransformQuery.ContentfulEntryModel
import com.contentful.java.cda.TransformQuery.ContentfulSystemField

@ContentfulEntryModel(value = "meetingPlacePageTenantList",
    additionalModelHints = [CMSTenantShopContentfulDTO::class, CMSTenantEntertainmentContentfulDTO::class, CMSTenantFoodBeverageContentfulDTO::class])
class CMSTenantListContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("tenants")
    val tenants: List<Any>? = null
}
```

Second Nested Entry
```
import com.contentful.java.cda.TransformQuery.ContentfulEntryModel
import com.contentful.java.cda.TransformQuery.ContentfulField
import com.contentful.java.cda.TransformQuery.ContentfulSystemField

@ContentfulEntryModel("meetingPlacePageTenantShop")
class CMSTenantShopContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("socialMediaLinks")
    val socialMediaLinks: CMSSocialMediaContentfulDTO?= null
    @ContentfulField("brand")
    val brand: CMSBrandShopContentfulDTO? = null

}
```

Third Nested Entry (The one which is not getting unwrapped/populated)
```
import com.contentful.java.cda.CDAAsset
import com.contentful.java.cda.CDAEntry
import com.contentful.java.cda.TransformQuery.*
import com.contentful.java.cda.rich.CDARichDocument

@ContentfulEntryModel("libraryBrandShop")
class CMSBrandShopContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("name")
    val name: String?=null

}
```

Also, the socialMediaLinks in the second nested entry are getting populated just fine, the issue is only with the brand field.

Here's the relevant snippet from the content model

```
{
            "sys": {
                "space": {
                    "sys": {
                        "type": "Link",
                        "linkType": "Space",
                        "id": ""
                    }
                },
                "id": "meetingPlacePageTenantShop",
                "type": "ContentType",
                "createdAt": "2022-09-30T08:37:57.465Z",
                "updatedAt": "2022-12-07T13:20:54.000Z",
                "environment": {
                    "sys": {
                        "id": "master",
                        "type": "Link",
                        "linkType": "Environment"
                    }
                },
                "revision": 11
            },
            "displayField": "internalName",
            "name": "",
            "description": "",
            "fields": [
                {
                    "id": "brand",
                    "name": "Brand",
                    "type": "Link",
                    "localized": false,
                    "required": false,
                    "disabled": false,
                    "omitted": false,
                    "linkType": "Entry",
                    "validations": [
                        {
                            "linkContentType": [
                                "libraryBrandShop"
                            ]
                        }
                    ]
                },
                {
                    "id": "internalName",
                    "name": "Internal name",
                    "type": "Symbol",
                    "localized": false,
                    "required": false,
                    "disabled": false,
                    "omitted": false
                },
                {
                    "id": "name",
                    "name": "Name",
                    "type": "Symbol",
                    "localized": false,
                    "required": false,
                    "disabled": false,
                    "omitted": false
                },
```

Finally the CDA Client snippet

```
       val client = CDAClient.builder()
            .setSpace(spaceId)
            .setToken(cdaAccessToken)
            .build()

        val result = client
            .observeAndTransform(CMSMeetingPlaceContentfulDTO::class.java)
            .include(10)
            .all()
```

**Comment by shikhar-truminds** [comment]
Attaching the complete code of the main classes 

'''
import com.contentful.java.cda.CDAAsset
import com.contentful.java.cda.TransformQuery.ContentfulEntryModel
import com.contentful.java.cda.TransformQuery.ContentfulField
import com.contentful.java.cda.TransformQuery.ContentfulSystemField

@ContentfulEntryModel("libraryMeetingPlace")
class CMSMeetingPlaceContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("businessUnitCode")
    val mpId: String? = null
    @ContentfulField("name")
    val name: String = ""
    @ContentfulField("logo")
    val logo: CDAAsset? = null
    @ContentfulField("occationListPage")
    val occationListPage: CMSMeetingPlaceOccasionsContentfulDTO? = null
    @ContentfulField("tenantListPage")
    val tenantListPage: CMSTenantListContentfulDTO? = null
    @ContentfulField("mainBannerList")
    val bannerList: CMSBannerListContentfulDTO? = null
    @ContentfulField("openingHours")
    val openingHours: CMSOpeningHoursContentfulDTO?= null
    @ContentfulField("openingHoursExceptions")
    val openingHoursExceptions: List<CMSOpeningHoursExceptionContentfulDTO>? = null
    @ContentfulField("primaryLanguage")
    val primaryLanguage: CMSLanguageContentfulDTO? = null
    @ContentfulField("languages")
    val languages: List<CMSLanguageContentfulDTO>? = null
    @ContentfulField("timezone")
    val timezone: String? = null
    @ContentfulField("country")
    val country: CMSCountryContentfulDTO? = null
    @ContentfulField("coordinates")
    val coordinates: Map<String, Double>? = null
    @ContentfulField("floorPlanId")
    val floorPlanId: String?= null
    @ContentfulField("newsletterSubscriptionCode")
    val newsletterSubscriptionCode: String?= null
    @ContentfulField("phoneNumber")
    val phoneNumber: String?=null
    @ContentfulField("eMailAddress")
    val eMailAddress: String?=null
    @ContentfulField("contactUsEMailAddress")
    val contactUsEMailAddress: String?=null
    @ContentfulField("visitorsAddressStreet")
    val visitorsAddressStreet: String?=null
    @ContentfulField("visitorsAddressStreet2")
    val visitorsAddressStreet2: String?=null
    @ContentfulField("visitorsAddressZipCode")
    val visitorsAddressZipCode: String?=null
    @ContentfulField("visitorsAddressCity")
    val visitorsAddressCity: String?=null
    @ContentfulField("socialMediaLinks")
    val socialMediaLinks: CMSSocialMediaContentfulDTO? = null
    @ContentfulField("webUrl")
    val webUrl: String? = null
    @ContentfulField("serviceListPage")
    val serviceListPage: CMSServiceListPageContentfulDTO? = null
    @ContentfulField("eventListPage")
    val eventListPage: CMSEventListPageContentfulDTO? = null
    @ContentfulField("newsListPage")
    val newsListPage: CMSNewsListPageContentfulDTO? = null
    @ContentfulField("offerListPage")
    val offerListPage: CMSOfferListPageContentfulDTO? = null
    @ContentfulField("tenantEntertainmentListPage")
    val tenantEntertainmentListPage: CMSTenantEntertainmentListPageContentfulDTO? = null
    @ContentfulField("tenantFoodBeverageListPage")
    val tenantFoodBeverageListPage: CMSTenantFoodBeverageListPageContentfulDTO? = null
    @ContentfulField("tenantShopListPage")
    val tenantShopListPage: CMSTenantShopListPageContentfulDTO? = null

}
'''

'''
import com.contentful.java.cda.TransformQuery
import com.contentful.java.cda.TransformQuery.ContentfulField
import com.contentful.java.cda.TransformQuery.ContentfulSystemField
import com.contentful.java.cda.TransformQuery.ContentfulEntryModel

@ContentfulEntryModel("librarySocialMediaLinks")
class CMSSocialMediaContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("twitterUrl")
    val twitterUrl: String? = null
    @ContentfulField("facebookUrl")
    val facebookUrl: String? = null
    @ContentfulField("snapchatUrl")
    val snapchatUrl: String? = null
    @ContentfulField("instagramUrl")
    val instagramUrl: String? = null
    @ContentfulField("whatsAppUrl")
    val whatsAppUrl: String? = null
    @ContentfulField("tikTokUrl")
    val tikTokUrl: String? = null
    @ContentfulField("youTubeUrl")
    val youTubeUrl: String? = null
    @ContentfulField("telegramUrl")
    val telegramUrl: String? = null
    @ContentfulField("tripadvisorUrl")
    val tripadvisorUrl: String? = null
    @ContentfulField("webUrl")
    val webUrl: String? = null
    @ContentfulField("linkedInUrl")
    val linkedInUrl: String? = null
    @ContentfulField("pinterestUrl")
    val pinterestUrl: String? = null
    @ContentfulField("vkontakteUrl")
    val vkontakteUrl: String? = null
}

'''

'''
import com.contentful.java.cda.TransformQuery.ContentfulField
import com.contentful.java.cda.TransformQuery.ContentfulEntryModel
import com.contentful.java.cda.TransformQuery.ContentfulSystemField

@ContentfulEntryModel(value = "meetingPlacePageTenantList",
    additionalModelHints = [CMSTenantShopContentfulDTO::class, CMSTenantEntertainmentContentfulDTO::class, CMSTenantFoodBeverageContentfulDTO::class])
class CMSTenantListContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("name")
    val name: String? = null
    @ContentfulField("seoDescription")
    val seoDescription: String? = null
    @ContentfulField("tenants")
    var tenants: List<Any>? = null
    @ContentfulField("slug")
    val slug: String?= null
}

'''
import com.contentful.java.cda.CDAAsset
import com.contentful.java.cda.CDAEntry
import com.contentful.java.cda.TransformQuery.ContentfulEntryModel
import com.contentful.java.cda.TransformQuery.ContentfulField
import com.contentful.java.cda.TransformQuery.ContentfulSystemField
import com.contentful.java.cda.rich.CDARichDocument

@ContentfulEntryModel("meetingPlacePageTenantShop")
class CMSTenantShopContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("name")
    val name: String?= null
    @ContentfulField("floorPlanId")
    val floorPlanId: String?= null
    @ContentfulField("logo")
    val logo: CDAAsset?= null
    @ContentfulField("description")
    val description: CDARichDocument?= null
    @ContentfulField("seoDescription")
    val seoDescription: String?= null
    @ContentfulField("contactDetails")
    val contactDetails: CDARichDocument?= null
    @ContentfulField("coverImage")
    val coverImage: CDAAsset?= null
    @ContentfulField("openingHours")
    val openingHours: CMSOpeningHoursContentfulDTO?= null
    @ContentfulField("socialMediaLinks")
    val socialMediaLinks: CMSSocialMediaContentfulDTO?= null
    @ContentfulField("keyPartner")
    val keyPartner: Boolean?= null
    @ContentfulField("primaryCategory")
    val primaryCategory: CDAEntry? = null
    @ContentfulField("secondaryCategories")
    val secondaryCategories: List<CDAEntry>? = null
    @ContentfulField("brand")
    val brand: CMSBrandShopContentfulDTO? = null
    @ContentfulField("slug")
    val slug: String?= null

}

'''

import com.contentful.java.cda.CDAAsset
import com.contentful.java.cda.CDAEntry
import com.contentful.java.cda.TransformQuery.*
import com.contentful.java.cda.rich.CDARichDocument

@ContentfulEntryModel("libraryBrandShop")
class CMSBrandShopContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("name")
    val name: String?=null
    @ContentfulField("description")
    val description: CDARichDocument?=null
    @ContentfulField("seoDescription")
    val seoDescription: String?=null
    @ContentfulField("logo")
    val logo: CDAAsset?=null
    @ContentfulField("coverImage")
    val coverImage: CDAAsset?=null
    @ContentfulField("primaryCategory")
    val primaryCategory: CDAEntry?=null
    @ContentfulField("secondaryCategories")
    val secondaryCategories: List<CDAEntry>?=null
    @ContentfulField("socialMediaLinks")
    val socialMediaLinks: CMSSocialMediaContentfulDTO?= null

}

'''

import com.contentful.java.cda.CDAAsset
import com.contentful.java.cda.CDAEntry
import com.contentful.java.cda.TransformQuery.ContentfulEntryModel
import com.contentful.java.cda.TransformQuery.ContentfulField
import com.contentful.java.cda.TransformQuery.ContentfulSystemField
import com.contentful.java.cda.rich.CDARichDocument

@ContentfulEntryModel("meetingPlacePageTenantFoodBeverage")
class CMSTenantFoodBeverageContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("name")
    val name: String?= null
    @ContentfulField("floorPlanId")
    val floorPlanId: String?= null
    @ContentfulField("logo")
    val logo: CDAAsset?= null
    @ContentfulField("description")
    val description: CDARichDocument?= null
    @ContentfulField("seoDescription")
    val seoDescription: String?= null
    @ContentfulField("contactDetails")
    val contactDetails: CDARichDocument?= null
    @ContentfulField("coverImage")
    val coverImage: CDAAsset?= null
    @ContentfulField("openingHours")
    val openingHours: CMSOpeningHoursContentfulDTO?= null
    @ContentfulField("socialMediaLinks")
    val socialMediaLinks: CMSSocialMediaContentfulDTO?= null
    @ContentfulField("keyPartner")
    val keyPartner: Boolean?= null
    @ContentfulField("primaryCategory")
    val primaryCategory: CDAEntry? = null
    @ContentfulField("secondaryCategories")
    val secondaryCategories: List<CDAEntry>? = null
    @ContentfulField("cuisine")
    val cuisine: List<CMSCuisineContentfulDTO>? = null
    @ContentfulField("priceLevel")
    val priceLevel: CMSPriceLevelContentfulDTO? = null
    @ContentfulField
    val brand: CMSBrandFoodBeverageContentfulDTO? = null
    @ContentfulField("slug")
    val slug: String? = null


}

'''

import com.contentful.java.cda.CDAAsset
import com.contentful.java.cda.CDAEntry
import com.contentful.java.cda.TransformQuery.*
import com.contentful.java.cda.rich.CDARichDocument

@ContentfulEntryModel("libraryBrandFoodBeverage")
class CMSBrandFoodBeverageContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("name")
    val name: String?=null
    @ContentfulField("description")
    val description: CDARichDocument?=null
    @ContentfulField("seoDescription")
    val seoDescription: String?=null
    @ContentfulField("logo")
    val logo: CDAAsset?=null
    @ContentfulField("coverImage")
    val coverImage: CDAAsset?=null
    @ContentfulField("primaryCategory")
    val primaryCategory: CDAEntry?=null
    @ContentfulField("secondaryCategories")
    val secondaryCategories: List<CDAEntry>?=null
    @ContentfulField("cuisine")
    val cuisine: List<CMSCuisineContentfulDTO>?=null
    @ContentfulField("priceLevel")
    val priceLevel: CMSPriceLevelContentfulDTO?=null
    @ContentfulField("socialMediaLinks")
    val socialMediaLinks: CMSSocialMediaContentfulDTO?= null

}

'''

import com.contentful.java.cda.CDAAsset
import com.contentful.java.cda.CDAEntry
import com.contentful.java.cda.TransformQuery.ContentfulEntryModel
import com.contentful.java.cda.TransformQuery.ContentfulField
import com.contentful.java.cda.TransformQuery.ContentfulSystemField
import com.contentful.java.cda.rich.CDARichDocument

@ContentfulEntryModel("meetingPlacePageTenantEntertainment")
class CMSTenantEntertainmentContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("name")
    val name: String?= null
    @ContentfulField("floorPlanId")
    val floorPlanId: String?= null
    @ContentfulField("logo")
    val logo: CDAAsset?= null
    @ContentfulField("description")
    val description: CDARichDocument?= null
    @ContentfulField("seoDescription")
    val seoDescription: String?= null
    @ContentfulField("contactDetails")
    val contactDetails: CDARichDocument?= null
    @ContentfulField("coverImage")
    val coverImage: CDAAsset?= null
    @ContentfulField("openingHours")
    val openingHours: CMSOpeningHoursContentfulDTO?= null
    @ContentfulField("socialMediaLinks")
    val socialMediaLinks: CMSSocialMediaContentfulDTO?= null
    @ContentfulField("keyPartner")
    val keyPartner: Boolean?= null
    @ContentfulField("primaryCategory")
    val primaryCategory: CDAEntry? = null
    @ContentfulField("secondaryCategories")
    val secondaryCategories: List<CDAEntry>? = null
    @ContentfulField("brand")
    val brand: CMSBrandEntertainmentContentfulDTO? = null
    @ContentfulField("slug")
    val slug: String? = null
}

'''

import com.contentful.java.cda.CDAAsset
import com.contentful.java.cda.CDAEntry
import com.contentful.java.cda.TransformQuery.*
import com.contentful.java.cda.rich.CDARichDocument

@ContentfulEntryModel("libraryBrandEntertainment")
class CMSBrandEntertainmentContentfulDTO {
    @ContentfulSystemField("id")
    val id: String?=null
    @ContentfulSystemField("createdAt")
    val createdAt: String?=null
    @ContentfulSystemField("updatedAt")
    val updatedAt: String?=null
    @ContentfulField("name")
    val name: String?=null
    @ContentfulField("description")
    val description: CDARichDocument?=null
    @ContentfulField("seoDescription")
    val seoDescription: String?=null
    @ContentfulField("logo")
    val logo: CDAAsset?=null
    @ContentfulField("coverImage")
    val coverImage: CDAAsset?=null
    @ContentfulField("primaryCategory")
    val primaryCategory: CDAEntry?=null
    @ContentfulField("secondaryCategories")
    val secondaryCategories: List<CDAEntry>?=null
    @ContentfulField("socialMediaLinks")
    val socialMediaLinks: CMSSocialMediaContentfulDTO?= null

}

'''

Also, an additional observation, when fetching just the list of CMSTenantShopContentfulDTO or CMSTenantEntertainmentContentfulDTO or CMSTenantFoodBeverageContentfulDTO, brand is populated correctly but primary category field in brand is not populated (for all include levels from 1 to 10)

**Comment by rafalniski** [comment]
Hey @shikhar-truminds,

I was partially able to reproduce the issue locally - can you please try adding `CMSBrandShopContentfulDTO` into the `additionalModelHints` in the `CMSTenantListContentfulDTO`? So that the class looks like this:

`@TransformQuery.ContentfulEntryModel(value = "meetingPlacePageTenantList",
        additionalModelHints = [CMSTenantShopContentfulDTO::class, CMSBrandShopContentfulDTO::class, CMSTenantEntertainmentContentfulDTO::class, CMSTenantFoodBeverageContentfulDTO::class])`
        
For the `primaryCategory` you probably still need to create a `@ContentfulEntryModel` for it to be unwrapped correctly.
Let me know please if it changes anything on your side.

**Comment by shikhar-truminds** [comment]
@rafalniski I was able to get it to work using the approach you mentioned. Adding the model for primary category in the additional model hints fetched the primary category data as well. Thanks!

**Comment by rafalniski** [comment]
@shikhar-truminds Great!
