### ISSUE TITLE
CDARichHyperLink class is missing "uri" property under "data"

### ISSUE THREAD

**Issue by khanmuqeetkhan** [contentful/contentful.java#277]
When using Contentful Java SDK version 10.5.11. 

CDARichHyperLink class contains data as "java.lang.Object" whereas the json data fetched directly from https://cdn.contentful.com/spaces/<space>/environments/<env/entries/<entry-id> represents a hyperlink used in the RichText as 

           `{
              "nodeType": "hyperlink",
              "data": {
                "uri": "https://www.url..." 
              },
              "content": [
                {
                  "nodeType": "text",
                  "value": "test",
                  "marks": [],
                  "data": {}
                }
              ]
            },`

We expect CDARichHyperLink class to also represent the same structure as in the above JSON object i.e "data" should contain a property "uri" of type string.

**Comment by rafalniski** [comment]
Hey, 

`hyperlink` can be an instance of many classes like `CDAAsset` or `CDAEntry`. That's why it's an `Object` that we resolve depending on the JSON structure. In this case, we map uri to the `data` object, so that you can get the URI by calling `link.getData()`.
