### ISSUE TITLE
Embedded inline entry within heading in RTE not being resolved in returned fields

### ISSUE THREAD

**Issue by eliseboinnot** [contentful/contentful.java#282]
Similar to https://github.com/contentful/contentful.java/issues/265, embedded inline entry within a heading in a rich text are not being resolved, regardless of the number of include.

Example with the following entry:
<img width="744" alt="Screenshot 2023-04-02 at 10 32 07 am" src="https://user-images.githubusercontent.com/55349320/229324154-e53adbd9-1e97-4b1b-8ee1-92bc162ca090.png">
which returns:
<img width="727" alt="Screenshot 2023-04-02 at 10 19 29 am" src="https://user-images.githubusercontent.com/55349320/229324323-16ff53f3-1e89-440e-a6d2-091c1d63368d.png">

Note how the type of `data` in the first inline embed is `LinkedTreeMap` (inside a heading), whereas it's `CDAEntry`, as expected, when the embed is within a paragraph.

**Comment by rafalniski** [comment]
Hey @eliseboinnot thanks for the insights, the issue should be fixed in the latest release - v.10.5.14
