### ISSUE TITLE
Make Authorization Header in Exception configurable

### ISSUE THREAD

**Issue by monsdroid** [contentful/contentful.java#293]
Hiho, 

we have seen some Authorization Headers in in the Log if we just toString the CDAHttpException.
Could you make it configurable on Client creation to log sensible stuff or not in case of exception?

Thanks

**Comment by rafalniski** [comment]
Hey @monsdroid I created PR for it here: https://github.com/contentful/contentful.java/pull/294 Could you please take a look and let me know if that works for you? I can then deploy this to production release.

**Comment by monsdroid** [comment]
we gonna use this a soon as its gonna be released. 
personally i wouldn't mask all the headers, just the auth ones. this said i do not kow which headers are set on which case and what kind of sensitive data there can be. 
For our case masking of the "Authorization" header is sufficient. 

Thanks a lot

**Comment by rafalniski** [comment]
Released in `v.10.5.17`
