### ISSUE TITLE
Feature Request: add avif format to ImageOptions

### ISSUE THREAD

**Issue by erictraaaan** [contentful/contentful.java#296]
The `avif` image format is not available within the `Format` enum in `ImageOption.java`.

While we can specify the avif format directly in the URL we use to get an image (e.g. `https://images.ctfassets.net/.../my-image.jpg?fm=avif`, we have been using the `ImageOption` functionality when getting a `CDAAsset`'s URL through the `urlForImageWith()` function to abstract away the implementation of the parameters for better future compatibility.

Adding support for the `avif` image format will allow us to support the modern standard within our application using the existing `ImageOption` features available in the SDK.

![image](https://github.com/contentful/contentful.java/assets/16770078/dbfb4a2d-e8e6-42cb-8513-a4700fb553e9)

**Comment by rafalniski** [comment]
This one should be released in `10.5.18`
