### ISSUE TITLE
Feature request: rich-text-plain-text-renderer

### ISSUE THREAD

**Issue by thalen** [contentful/contentful.java#299]
When using JS there is an option to use [https://www.npmjs.com/package/@contentful/rich-text-plain-text-renderer](url)

Could this functionality be added to this repo? We have a requirement to extract all texts from a rich text field, and rich-text-plain-text-renderer does the job. Unfortunately it is not available in Java.

**Comment by rafalniski** [comment]
Hey @thalen,

unfortunately, there are no plans for creating such a library in Java currently. I suggest using https://github.com/contentful/rich-text-renderer-java/tree/master/html and then picking the plain text from the output HTML on your end.
