### ISSUE TITLE
Improvement - Debugging Error Messages

### ISSUE THREAD

**Issue by jameshays** [contentful/contentful.java#60]
I'm debugging an issue where I'm have a model called States with two fields, "stateName" and "abbreviation".  I'm running a query in which I specify "content_type" and "fields.abbreviation" in a Map<String, String> and call .entries().fetchAll(map).  I'm getting a 400 Bad Request.  If I remove the "fields.abbreviation" query item it works just fine so it's clearly something with that piece, but I can't tell what.  Can you improve the error response to contain a bit more information as to what it doesn't like?

**Comment by jameshays** [comment]
I found it needed the [match] addition to the query param name

**Comment by tomxor** [comment]
@jameshays Please setup your client with .setLogLevel(LogLevel.FULL) and paste the logs for the request.

**Comment by tomxor** [comment]
In the future you can use `setLogLevel(LogLevel.FULL)` to see the actual logs for the request. If there is no problem please resolve the issue.
