### ISSUE TITLE
Online java documentation is not up to date?

### ISSUE THREAD

**Issue by butenkor** [contentful/contentful.java#61]
Can it be that your documentation:
https://www.contentful.com/developers/documentation/content-delivery-api/java/#search-content-type
is not up to date with current java sdk version anymore: https://github.com/contentful/contentful.java/releases/tag/2.0.1?

**Comment by tomxor** [comment]
Yes, apologies for that. We will update it in the next couple of days. In the meantime the JavaDoc for the library is available here: http://contentful.github.io/contentful.java/ and there's also a migration guide in the wiki: https://github.com/contentful/contentful.java/wiki/2.0-Migration

Thanks for the report!

**Comment by tomxor** [comment]
@butenkor updated on the website: https://www.contentful.com/developers/documentation/content-delivery-api/java/

Thanks again :+1:

**Comment by butenkor** [comment]
Thanks!
