### ISSUE TITLE
Content decoding

### ISSUE THREAD

**Issue by butenkor** [contentful/contentful.java#72]
Current client implementation relies on JVM charset setting for body decoding
(https://github.com/contentful/contentful.java/blob/master/src/main/java/com/contentful/java/cda/BaseModule.java#L104). Unfortunately JVMs default charset very often it is not UTF-8. According to doc (https://www.contentful.com/developers/documentation/content-delivery-api/http/#encoding) UTF-8 is default encoding for contentful API anyway so it would be nice if client would use this decoding as default  or at least provide a way to define decoding type to be used for client users.

**Comment by tomxor** [comment]
:+1: thanks for the bug report!

**Comment by butenkor** [comment]
@tomxor Do you have an idea when it is going to be fixed/released?

**Comment by tomxor** [comment]
@butenkor I was planning to push this into the next major release we're planning, but might as well quick-fix and release a small update. Should be available in the next few hours.

**Comment by tomxor** [comment]
@butenkor I would just hardcode it to UTF-8, do you have a specific use-case for manually providing a different charset when creating a client?

**Comment by tomxor** [comment]
(considering only UTF-8 is supported by the API)

**Comment by butenkor** [comment]
Fine be me, thanks!

**Comment by butenkor** [comment]
If you are able to provide quick fix would be nice too!

**Comment by tomxor** [comment]
@butenkor Just pushed 2.0.4 to SonaType with the fix, should be available via Maven within 10 minutes or so. Thanks again!

**Comment by butenkor** [comment]
:+1:
