### ISSUE TITLE
Unpublished resources in production mode

### ISSUE THREAD

**Issue by butenkor** [contentful/contentful.java#77]
If CMS page element contains a list of ```CDAEntries``` and one of this entries is not published then unpublished elements will be of type [LinkedTreeMap](https://code.google.com/p/google-gson/source/browse/trunk/gson/src/main/java/com/google/gson/internal/LinkedTreeMap.java?r=1225). Its not very useful as its information contains only some meta data and in production mode one would not be interested in unpublished content. Is it possible that API does not return unpublished elements in production mode?

**Comment by tomxor** [comment]
The API does not return any unpublished results when you query against the production server. However, if you have a relationship where one entry points to another one (i.e. via link / array of links) - if you unpublish the second entry, when making a request it will still contain link information to that entry, even though it is unpublished. Currently there is some inconsistency as a field may contain either the linked resource or as you said a `Map` representing the link details, which are not very useful. A temporary workaround until #75 is fixed would be to call `nullifyUnresolvedLinks()` on the `CDAClient.Builder`.

**Comment by tomxor** [comment]
@butenkor does that resolve your problem?

**Comment by butenkor** [comment]
@tomxor Thanks, should have found that function by myself :) You may close the ticket if you want.
